# Generated by Django 3.1.2 on 2021-04-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210412_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type',
        ),
        migrations.AddField(
            model_name='animal',
            name='genres',
            field=models.ManyToManyField(help_text='Select a genre for this film', to='blog.Type'),
        ),
        migrations.AddField(
            model_name='animal',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='film/posters/%Y/%m/%d/', verbose_name='Poster'),
        ),
    ]
