# Generated by Django 3.1.2 on 2021-04-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210412_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='genres',
            new_name='type',
        ),
    ]
