# Generated by Django 3.1.2 on 2021-06-11 15:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210412_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.poster_path, verbose_name='Poster'),
        ),
    ]
